### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [0xFireball/Enlightened#1]
Would you consider making the `.apk` available here at Github, so folks without Playstore can take a look?

**Comment by 0xFireball** [comment]
Absolutely!
I'll do it as soon as I get back to my computer!



On Sat, Dec 3, 2016 at 5:10 AM -0800, "Izzy" <notifications@github.com<mailto:notifications@github.com>> wrote:


Would you consider making the .apk available here at Github, so folks without Playstore can take a look?

-

**Comment by IzzySoft** [comment]
Thanks a lot! I'll get a note then when you close this issue afterwards. Suggestion: Mention the APKs location on the main `README.md` to make it easy to find :smile_cat:

**Comment by 0xFireball** [comment]
Thanks for the suggestion, I've updated the page! I'll be uploading the APK files shortly

**Comment by 0xFireball** [comment]
@IzzySoft here you go! https://github.com/0xFireball/Enlightened/releases/tag/apk25

**Comment by IzzySoft** [comment]
Wonderful, thanks! If you want to add another download URL/method: the F-Droid client can be used to install/update [from here](https://apt.izzysoft.de/fdroid/index/apk/xyz.iridiumion.enlightened) now. Updates should show up within 24h after you've added them to a tag on the `releases/` page :smile_cat:

**Comment by 0xFireball** [comment]
Ooh, thanks! I'm happy to see my app on an F-Droid repo!
I'm sure you will understand: I would just like to gently request that you please distribute the official builds signed by me. Those builds on GitHub releases are signed, and perfectly OK to distribute 😉
If you can, please indicate that the app is still in alpha! 🙂



On Sat, Dec 3, 2016 at 6:05 PM -0800, "Izzy" <notifications@github.com<mailto:notifications@github.com>> wrote:


Wonderful, thanks! If you want to add another download URL/method: the F-Droid client can be used to install/update from here<https://apt.izzysoft.de/fdroid/index/apk/xyz.iridiumion.enlightened> now. Updates should show up within 24h after you've added them to a tag on the releases/ page 😸

**Comment by IzzySoft** [comment]
> I would just like to gently request that you please distribute the official builds signed by me.

That is what I do – and that is why I needed the ' .apk` published here at Github, and why I wrote *Updates should show up within 24h after you've added them* – I just pick the APK files. Other than the main repo, I don't rebuild them, so your signature remains intact and cross-updating with the playstore is possible.

> If you can, please indicate that the app is still in alpha!

That's part of the file name as long as you have it in the version number: `xyz.iridiumion.enlightened_1.7-alpha2.apk`, as files are named `<package_name>_<version>.apk` here. I didn't mention that in the description as I might miss when you reach stable versions (updates are automated here). I hope that's fine with you, and sufficient.

**Comment by IzzySoft** [comment]
PS: I just see my updater uses the *tag* for the version number – which in your case reflects the versionCode instead of the versionName. Any special reason for that? First time I encounter that here at Github ;)

**Comment by 0xFireball** [comment]
About what you stated: sounds great, and thanks for setting this up!

The reason I'm using `versionCode` for now is because the version names are somewhat arbitrarily chosen. There's really no good other reason than that I couldn't remember the corresponding version name 😛.

I'll eventually switch to more normal version names.

**Comment by IzzySoft** [comment]
OK, and no worries: I just checked, and the version number stating "Alpha" in big letters is still there, being the header for the corresponding file section:

[![screenshot](https://i.imgur.com/qH2kSHat.png)](https://i.imgur.com/qH2kSHa.png)

The F-Droid client on Android should show it in a similar manner. Just verified: it is :smiley_cat:
