### ISSUE TITLE
German language support

### ISSUE THREAD

**Issue by FriederZi** [0xFireball/Enlightened#14]
Add a German strings.xml, I can translate it for you.

**Comment by steveoh92** [comment]
I can help with translation too.

_Sent from my HUAWEI WAS-LX1A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 0xFireball** [comment]
I'll push out an update soon that will allow translators to contribute.
Thanks for your willingness to help! 😄

**Comment by 0xFireball** [comment]
@steveoh92 What language would you like to translate?

**Comment by 0xFireball** [comment]
Hi @FriederZi, as of https://github.com/0xFireball/Enlightened/commit/12c844092999b663dc5806f35181d48c74fe80e4 there is now a strings XML file for the `de` (German) locale.
For now, it's in the `localization` branch.

Thanks for your help!

**Comment by 0xFireball** [comment]
Hello @steveoh92, what language would you like to help with?
If you're interested, please create another issue/PR, and I'll add the relevant XML file.
