### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by Cj-Malone** [0xFireball/Enlightened#2]
Could spell check be enabled, maybe just with txt/NoHighlightingDefinition I could understand it being annoying in source files.

Also a line wrap option? Maybe a setting, not laguage related.

(Found this in F-Droid, I like it so far)

**Comment by 0xFireball** [comment]
Thanks for mentioning these! I'll also add an indent size customizer, because some people like 2-space indents

**Comment by TheDiamondYT1** [comment]
Imo, you should make it a bit like AIDE; have a whole settings screen just for the editor
