### ISSUE TITLE
SFTP/cloud storage support

### ISSUE THREAD

**Issue by psycholyzern** [0xFireball/Enlightened#20]
It would be nice if this app can edit files over SFTP. Also adding dropbox/gdrive/other cloud storage, would be very nice.

**Comment by 0xFireball** [comment]
I think this adds unnecessary bloat. Please consider using a separate app for this.

**Comment by psycholyzern** [comment]
Cloud might be a bloat but I don't SFTP is a bloat too. Since this is a coding app, and people use server to host scripts, those scripts can be edited through SFTP directly. It is much efficient than download the script using another app, edit it using Enlightened, reupload using another app.
But it is okay if you insist.

**Comment by 0xFireball** [comment]
I believe DroidEdit has this feature. I recommend you use an app like that if you really need it; but for this project, I want to keep it as minimal as possible.

Thanks for your suggestion.

**Comment by psycholyzern** [comment]
DroidEdit is pretty much dead. Bugs exist and dev doesn't reply to emails. If you can see in Playstore, the last update was recently but the truth is he pushed an update with no fix/improvements. Last true update was 2015 or 2016 I don't remember.
Btw, no problem with your decision. This app might be useful to other people.
Thanks.
