### ISSUE TITLE
Make it easier for you and me

### ISSUE THREAD

**Issue by nickbrin** [0xFireball/Enlightened#22]
Hey just had a quick idea. Instead of programming support for all kinds of different syntax. Why not have a couple functions for referencing different documents and then use a document that THEY create for the syntax of other languages. Like this:

[functions]
#0v6578
draw_sprite(arg1, arg2, arg3)
draw_rectangle(arg1, arg2, arg3)

And then they can use what ever syntax we want while still keeping it lightweight.

**Comment by ShalokShalom** [comment]
https://langserver.org/

**Comment by 0xFireball** [comment]
Problem is, while implementing the language server protocol might not be too bad in itself, I think that actually introducing the code to run the different language servers would cause bloat. The main idea behind this project is to stay extremely lightweight.

**Comment by ShalokShalom** [comment]
Ah, I see.

**Comment by ShalokShalom** [comment]
Is there maybe another project, which already provides such code?

So, in order to use that as an optional, modular feature?

**Comment by 0xFireball** [comment]
Such a project might exist, but I don't know about one off the top of my head. You could definitely fork this project though and add the feature for now.

**Comment by 0xFireball** [comment]
@nickbrin, regarding custom syntax highlighting support, yes, that is planned, you will be able to make custom syntax configs that use regex highlighting (that's how it currently works, except right now the highlighting definitions are built-in).
