### ISSUE TITLE
[Suggest] Had a same project

### ISSUE THREAD

**Issue by kenneth-Q** [0xFireball/Enlightened#24]
Had same funsion project from github
https://github.com/jecelyin/920-text-editor-v2
Maybe you can fork it or help him fix the bug.
The another doesn't relase a new version for fix any bugs like (Backspace not working #1519).
I hope you can finish it.
Thanks.

**Comment by 0xFireball** [comment]
Hi, this is an interesting project, perhaps we can take a look at it when working on this one.
