### ISSUE TITLE
Ctrl , Alt , Shift , Arrow-Keys & Inbuilt Terminal.

### ISSUE THREAD

**Issue by geekfreak07** [0xFireball/Enlightened#25]
How  about adding the keys I mentioned by default for a more Desktop like feel and a basic Terminal environment?

**Comment by 0xFireball** [comment]
Hi, I think this adds unnecessary bloat to the project. You can always use one of the great terminal emulator apps or Termux if you need a Unix-like environment. If you want a desktop-like feel, maybe you could try Vim in Termux?
