### ISSUE TITLE
Useless permission

### ISSUE THREAD

**Issue by TheDiamondYT1** [0xFireball/Enlightened#3]
```xml
android.permission.READ_EXTERNAL_STORAGE
```
Is implicitly  granted to any app that has the permission 
```xml
android.permission.WRITE_EXTERNAL_STORAGE
```

To quote [the Android docs](https://developer.android.com/reference/android/Manifest.permission.html)

> Any app that declares the WRITE_EXTERNAL_STORAGE permission is implicitly granted this permission.

**Comment by 0xFireball** [comment]
Right, thanks for pointing this out.
