### ISSUE TITLE
Code Compeletion and other

### ISSUE THREAD

**Issue by Repugnus** [0xFireball/Enlightened#4]
I was thinking maybe you could add simple code completion like when you type one bracket another appears and it puts the cursor in between them, same for parentheses and quotes.

**Comment by Repugnus** [comment]
Also I meant to say adding ftp/sftp support

**Comment by 0xFireball** [comment]
i will add basic automatching for suported languages

i will not be adding ftp/sftp support; it is supposed to be minimal. if you need such a feature, feel free to use another app

**Comment by Repugnus** [comment]
Ok, thanks for the quick response and I can just use a file manager for ftp/sftp 

Thanks
