### ISSUE TITLE
Convert it to library

### ISSUE THREAD

**Issue by kal27** [0xFireball/Enlightened#6]
This would be immensely useful as a library since there are no libraries with edittext syntax highlighting functionality or at least I haven't found any

**Comment by 0xFireball** [comment]
Sure. I'll get to this soon.

**Comment by 0xFireball** [comment]
hello there @kal27 

I am glad to inform you that I just converted the `IridiumHighlightingEditorJ` to a library!
(see #7)

For now, you will have to use `Enlightened` as a Git submodule and import the `iridiumhighlightingeditor` android module into your project.

(You can find the library sources [here](https://github.com/0xFireball/Enlightened/tree/master/iridiumhighlightingeditor))
